name: node_auth
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: "^0.4.5"
  image: "^2.0.4"
  path: "^1.5.1"
  http: ^0.12.0
  flutter_stetho: ^0.2.2
  barcode_scan : "^0.0.4"
  


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/bg.jpg
   - assets/user.png
   - assets/logo.png
   - assets/input-barcode.png
   - assets/scan-barcode.png
   - assets/no-avatar.png
   - assets/empty.png
   - assets/full.png
   - assets/empty2.png
   - assets/full2.png
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Ubuntu
     fonts:
     - asset: assets/fonts/Ubuntu-Regular.ttf
   - family: Athletic
     fonts:
     - asset: assets/fonts/New-Athletic-M54.ttf
   - family: MyFlutterApp
     fonts:
     - asset: assets/fonts/MyFlutterApp.ttf
   - family: MyFlutterApp2
     fonts:
     - asset: assets/fonts/MyFlutterApp2.ttf
   - family: Pacifico
     fonts:
     - asset: assets/fonts/Pacifico.ttf  
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
